["ruby2.4"]
name = "Ruby 2.4"
desc = "Released on 2016.12.25"

["ruby2.5"]
name = "Ruby 2.5"
desc = "Released on 2017.12.25"

["ruby2.6"]
name = "Ruby 2.6"
desc = "Released on 2018.12.25"

["ruby2.7"]
name = "Ruby 2.7"
desc = "Released on 2019.12.25"
